// Hosting URLs — update these if you move the video/image assets
export const IMAGE_BASE   = 'https://adibuoy23.github.io/event_representations/video_frames/';
export const VIDEO_BASE   = 'https://adibuoy23.github.io/event_representations/videos/';
export const CLIP_TOTAL_S = 190.0;   // total clip duration in seconds (for frame-index math)

// Card style shared across panels
export const CARD = {
  backgroundColor: 'white',
  borderRadius: '10px',
  boxShadow: '0 1px 4px rgba(0,0,0,0.10), 0 0 0 1px rgba(0,0,0,0.04)',
  padding: '10px',
  boxSizing: 'border-box',
};

// All condition-specific constants (colors, labels, condition lists) are read
// at runtime from appData.meta, which is generated by scripts/generate_js_data.py.
// Do not add per-condition values here.
